"""Constants for the Template Climate integration."""

CONF_CLIMATES = "climates"
CONF_BASE_CLIMATE_ENTITY_ID = "base_climate_entity_id"
CONF_DEVICE_CLASS = "device_class"
CONF_STATE = "state"
CONF_TEMPERATURE_UNIT = "temperature_unit"
CONF_SERVICE_SCRIPTS = "service_scripts"
CONF_HVAC_MODE_SCRIPTS = "hvac_mode_scripts"
CONF_PRESET_MODE_SCRIPTS = "preset_mode_scripts"
CONF_FAN_MODE_SCRIPTS = "fan_mode_scripts"
CONF_SWING_MODE_SCRIPTS = "swing_mode_scripts"
CONF_SWING_HORIZONTAL_MODE_SCRIPTS = "swing_horizontal_mode_scripts"
CONF_SET_TEMPERATURE_SCRIPT = "set_temperature"
CONF_SET_HUMIDITY_SCRIPT = "set_humidity"
CONF_TURN_ON_SCRIPT = "turn_on"
CONF_TURN_OFF_SCRIPT = "turn_off"
CONF_TOGGLE_SCRIPT = "toggle"
